import Head from 'next/head';
import React, { FC } from 'react'
import { Navbar } from '../ui';

interface Props{
    title: string;
    description: string;
    children: React.ReactNode;
}

export const Portfolio: FC<Props> = ({ title, description, children }) => {
    return (
        <>
            <Head>
                <title>{ title }</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
            </Head>
            <Navbar />
            <main className='h-auto md:min-h-screen bg-primary'>
                { children }
            </main>
        </>
    )
}
